#ifndef   PURRENGINE_RENDERER_RENDERPASS_HPP_
#define   PURRENGINE_RENDERER_RENDERPASS_HPP_

#include <unordered_map>

namespace PurrfectEngine {

  struct purrPipelineCreateInfo {
    int width;
    int height;
    std::unordered_map<VkShaderStageFlagBits, const char *> shaders;
    purrTexture* colorTarget;
    purrTexture* depthTarget; // Can be set to nullptr if not needed. In that case, it will be automatically generated by the purrPipeline constructor.
  };

  class purrPipeline {
  public:
    purrPipeline(purrPipelineCreateInfo createInfo);
    ~purrPipeline();

    void initialize();

    void cleanup();

    // Binds render pass and pipeline, ready for rendering.
    // WARNING: There must be an active command buffer in the PurrfectEngineContext.
    void begin(VkClearValue clearColor);
    void end();

    static void setContext(PurrfectEngineContext *context);
  public:
    purrTexture *getColor() const { return mColorTexture; }
    purrTexture *getDepth() const { return mDepthTexture; }
  private:
    purrPipelineCreateInfo mCreateInfo{};
    fr::frRenderer *mRenderer = nullptr;

    fr::frRenderPass *mRenderPass = nullptr;
    fr::frPipeline *mPipeline = nullptr;

    purrTexture *mColorTexture = nullptr;
    purrTexture *mDepthTexture = nullptr;

    fr::frFramebuffer *mFramebuffer = nullptr;

    std::vector<fr::frShader*> mShaders{};
  };

}

#endif // PURRENGINE_RENDERER_RENDERPASS_HPP_