name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GCC
        run: sudo apt-get install -y gcc
      - name: Build with GCC
        run: |
          gcc -o nob nob.c
          ./nob init

  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang
        run: sudo apt-get install -y clang
      - name: Build with Clang
        run: |
          clang -o nob nob.c
          ./nob init

  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Clang on macOS
        run: |
          clang -o nob nob.c
          ./nob init

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build with MSVC on Windows
        run: |
          msbuild nob.c
          nob.exe init
