# Copied from https://github.com/tsoding/bm/blob/master/.github/workflows/ci.yml

name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          $CC -o nob nob.c
          ./nob init
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          $CC -o nob nob.c
          ./nob init
        env:
          CC: clang
          CXX: clang++
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build everything
        run: |
          $CC -o nob nob.c
          ./nob init
        env:
          CC: clang
          CXX: clang++
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - name: force LF
        shell: cmd
        run: |
          git config --global core.autocrlf input
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        shell: cmd
        run: |
          cl.exe nob.c
          .\nob.exe init